# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://docklandsljc.uk
title: Docklands.LJC
subtitle: The London Java Community for the Docklands
author: Rob Barr
simple_search: https://duckduckgo.com/
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:title.html
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: Tag
markdown: kramdown
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: rouge # default python pygments have been replaced by pygments.rb

paginate: 1          # Posts per page on the blog index
paginate_path: "Page/:num"   # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: false       # Converts page and post titles to titlecase

# Twitter
twitter_user: 
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true
